### ISSUE TITLE
Add /dictionary command using Google Dictionary API

### ISSUE THREAD

**Issue by marchingon12** [marchingon12/Perry#8]
- [x] Add loops for different meanings + definition
- [x] Implement buttons similar to /remwatchlist on acutebot (Next and cancel buttons)
- [x] Next button will show next definition + examples; if end of list then only cancel button will show.
- [x] Test locally on PlatapusEdgeBot and make sure everything is working.

Reason for adding module: having UrbanDictionary but no normal Dictionary is weird.

Using https://github.com/meetDeveloper/googleDictionaryAPI because it is multilingual with unlimited calls.

**Comment by starry-shivam** [comment]
![d537c28d7c970f0c8561760e02c510df](https://user-images.githubusercontent.com/58552395/103210195-fe5e9e80-492a-11eb-8f52-948989644e53.jpg)

**Comment by marchingon12** [comment]
![sticker (6)](https://user-images.githubusercontent.com/41235480/103239498-923d6400-4945-11eb-854f-21c46e258da3.png)
